version: '2'
services:
    microsite:
        image: openbudgets/microsite
        build: ./microsite
        volumes:
            - ../volumes/osviewer/themes:/microsite/os_viewer_themes
            - ../volumes/microsite/data/db.sqlite3:/microsite/db.sqlite3
        ports:
            - "8003:8000"
        links:
            - os-viewer
        environment:
            - OS_VIEWER_THEMES_FOLDER=os_viewer_themes
            #- OS_VIEWER_HOST=http://eis-openbudgets.iais.fraunhofer.de/viewer
            #- OS_API=http://eis-openbudgets.iais.fraunhofer.de
            - OS_VIEWER_HOST=http://apps.openbudgets.eu/viewer
            - OS_API=http://apps.openbudgets.eu
        env_file:
            - ../env.example
    silkworkbench:
        image: openbudgets/silkworkbench
        build: ./silkworkbench
        volumes:
            - ../volumes/silkworkbench/silk:/root/.silk
        ports:
            - "9000:9000"
    alignmentmysql:
        image: openbudgets/alignmentmysql
        build: ./alignmentmysql
        volumes:
            - ../volumes/alignment/mysql:/var/lib/mysql
        env_file:
            - ../env.example
        ports:
            - "3306:3307"
    alignment:
        image: openbudgets/alignment
        build: ./alignment
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/alignment/composer:/root/.composer/cache
        env_file:
            - ../env.example
        links:
            - alignmentmysql
    linkedpipes_fdp:
        image: openbudgets/linkedpipes
        build: ./linkedpipes
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
        ports:
            - "8181:8181" # Webserver & URI dereferencable URI for pipelines + templates
            - "8170:8170" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "2223-2230:2223-2230" # Linked Pipes FTP data psort
            - "8101:9101" # supervisord frontend
        links:
            - virtuoso_staging
            - sshserver
    sshserver:
        image: openbudgets/sshserver
        build: ./sshserver
        volumes:
            - ../volumes/nginx/dumps:/dumps
            - ../volumes/sshserver/log:/var/log
    virtuoso_staging:
        image: openbudgets/virtuoso
        build: ./virtuoso
        restart: always
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/virtuosoStaging/upload:/upload
            - ../volumes/nginx/dumps:/dumps
            - ./virtuoso/virtuoso.ini.dev:/virtuoso.ini
        env_file:
            - ../env.example
        environment:
            - SPARQL_UPDATE=true
        ports:
            - "8890:8890"
            - "1111:1111"
    virtuoso_production:
        image: openbudgets/virtuoso
        build: ./virtuoso
        restart: always
        volumes:
            - ../volumes/virtuosoProduction/data:/data
            - ../volumes/virtuosoStaging/data:/newdata
            - ./virtuoso/production/startVirtuoso.sh:/startVirtuoso.sh
            - ./virtuoso/virtuoso.ini.dev:/virtuoso.ini
        env_file:
            - ../env.example
        environment:
            - SPARQL_UPDATE=false
        ports:
            - "8891:8890"
            - "1112:1111"
    rudolf:
        image: openbudgets/rudolf
        build: ./rudolf
        links:
            - virtuoso_production
            - virtuoso_staging
    rdfbrowser:
        image: openbudgets/rdfbrowser
        build: ./rdfbrowser
        volumes:
            - ../volumes/rdfbrowser/storage/database.sqlite:/var/www/RDFBrowser/storage/database.sqlite
            - ./rdfbrowser/dev/apache2.conf:/etc/apache2/apache2.conf
        ports:
            - "8111:80"
        links:
            - virtuoso_staging
            - virtuoso_production
    dampostgres:
        image: openbudgets/dampostgres
        build: ./dampostgres
        volumes:
            - ../volumes/dam/dampostgres:/var/lib/postgresql/data
        env_file:
            - ../env.example
    damapp:
        image: openbudgets/damapp
        build: ./damapp
        ports:
            - "5000:5000"
        links:
            - dampostgres
        env_file:
            - ../env.example
    outlierdm:
        image: openbudgets/outlierdm
        build: ./outlierdm
        ports:
            - "5555:5000"
    nginx:
        image: openbudgets/nginx
        build: ./nginx
        restart: always
        volumes:
            - ./nginx/conf/nginx_dev.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/nginx/dumps:/var/www/dumps # serve rdf-file-dumps via http
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
            - ./nginx/static_files/images:/var/www/images
            - ./nginx/static_files/svg:/var/www/svg
        links:
            - linkedpipes_fdp
            - virtuoso_staging
            - virtuoso_production
            - rudolf
            - os-viewer
            - indigo
            - rdfbrowser
            - alignment
            - microsite
            - damapp
        ports:
            - "80:80" # http
            - "443:443" # https
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
    os-viewer:   #image: openspending/os-viewer
        image: openbudgets/os-viewer
        build: ./os-viewer
        expose:
          - "8000"
        ports:
          - "9003:8000"
        volumes:
            - ./os-viewer/dev_config:/config
            - ../volumes/osviewer/themes:/app/app/config/themes
        environment:
            - DEFAULT_HOST=http://localhost
            - DEFAULT_BASE_PATH=/viewer
            - OS_EXTERNAL_ADDRESS=http://localhost
            - OS_VIEWER_API_HOST=http://localhost
            - OS_VIEWER_AUTH_HOST=http://next.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://localhost
            - OS_VIEWER_DATAMINE_HOST=http://localhost
            #- OS_VIEWER_API_COSMO_HOST
            #- OS_VIEWER_BASE_PATH
    os-packager:
        build: ./os-packager
        restart: always
        expose:
          - "8000"
        ports:
          - "9552:8000" 
    indigo:
        image: openbudgets/indigo
        build: ./indigo
        ports:
          - "4200:4200"
        links:
          - damapp
    kpi:
        image: openbudgets/kpi
        build: ./kpi
        volumes:
            - ../volumes/kpi/database:/var/www/database
            #- ./kpi/dev/apache2.conf:/etc/apache2/apache2.conf
            - ../volumes/kpi/composer:/root/.composer
        ports:
            - "8112:80"

